### ISSUE TITLE
3D Printed parts are not available.

### ISSUE THREAD

**Issue by ero589** [HomeKidd/ESP8266-Homekit-Smart-Blinds#2]
Not sure if this is known but the 3D file links are missing in the wiki.

**Comment by HomeKidd** [comment]
This is a known "issue" because this project is still in development as shown in the [readme](https://github.com/HomeKidd/ESP8266-Homekit-Smart-Blinds/blob/master/README.md). Currently the 3D parts are not available, because the PCB design isnt completed yet and without the final PCB design i can't make a 3D printed case for it 😄
