### ISSUE TITLE
Hardware setup Wiki missing Images 

### ISSUE THREAD

**Issue by ero589** [HomeKidd/ESP8266-Homekit-Smart-Blinds#3]
Missing images from the hardware setup page.

**Comment by HomeKidd** [comment]
This is a known "issue" because this project is still in development as shown in the [readme](https://github.com/HomeKidd/ESP8266-Homekit-Smart-Blinds/blob/master/README.md). Currently the GPIO setup may change in future and this is why its not available yet 😄

The current setup is:

`IN1 - GPIO13`
`IN2 - GPIO14`
`IN3- GPIO16`
`IN4 - GPIO12`
