### ISSUE TITLE
Question — How to set endpoints for motors

### ISSUE THREAD

**Issue by Efiller91** [HomeKidd/ESP8266-Homekit-Smart-Blinds#4]
Considering implementing this — How do you set end points for motor rotation?

**Comment by HomeKidd** [comment]
Hi! 
Currently endpoints cannot be set because i have no time for developing that many HomeKit projects🤓

What i’m planning to do is - on first init - creating a “setup mode”, where you can setup the desired endpoint by moving the motor to position (eg.: fully closing/opening the blinds) via webUI or within HomeKit 🙌

**Comment by Efiller91** [comment]
Oh that’s be exactly what this needs to function! Thanks for the quick reply. I’ll be watching for the new functionality eagerly.

**Comment by komarofleo** [comment]
Dear HomeKid - you have the best firmware - can you add time of work functions - I mean the time of work stepper drive. It can help adjust positions of stop/close for blinds, tnahx a lot

**Comment by komarofleo** [comment]
or ability to control the number of steps ))

**Comment by arkn666l** [comment]
waiting for this function!
