### ISSUE TITLE
Firmware

### ISSUE THREAD

**Issue by Izac9** [HomeKidd/ESP8266-Homekit-Smart-Blinds#5]
Can you please upload uncompiled firmware ? Can I help you with this project ? I'm really interested in this project, but don't see updates.😔🖤

**Comment by HomeKidd** [comment]
Hi!
The source code never will be available because i have too many custom things (libraries, esp-homekit and even esp-open-rtos) and 99% of people cannot compile the code 🤓

Currently i have no time because of my main job and other, more important HomeKit projects (Garage Door opener, Weather Station and Alarm system controller) 😩 but this project will be finished in the near future ✌️😊
